# Generated by Django 4.2.5 on 2024-01-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
