# Generated by Django 4.2.5 on 2024-01-06 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_remove_note_author_remove_note_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
