# Generated by Django 4.2.5 on 2024-01-07 12:18

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_search_vector_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
